blank_issues_enabled: true
contact_links:
  - name: Question or idea
    url: https://github.com/i18n-inflect/i18n-inflect-js/discussions
    about: For usage questions and design discussion, open a discussion instead.
